export const apiRoutes = {
  signup: "/auth/register",
  existingUserCheck: "/auth/exist-user",
  requestNewPasswordLink: "/auth/request-password-setup",
  setNewPassword: "/auth/set-password",
  requestNewApprovalLink: "/auth/resend-approval-link",
  userVerifyAccount: "/auth/approve-account",
  login: "/auth/login",
  updateFreeTrial: (id: string) => `/users/${id}`,
  getAllergiesList: "/allergy",
  addAllergies: "/allergy",
  updateAllergy: (id: string) => `/allergy/${id}`,
  updatePrivacySetting: "/profile/privacy-settings",
  getPrivacySettings: "/profile/privacy-settings",
  changeSharePin: "/account/change-access-pin",
  changePassword: "/account/change-password",
  deactivateAccount: "/account/deactivate",
  cancelSubscription: "/account/cancel-subscription",
  getParticularUserList: (id: string) => `/users/${id}`,
  getSymptomList: "/symptoms",
  createSymptom: "/symptoms",
  updateSymptom: (id: string) => `/symptoms/${id}`,
  updateUserDetails: (id: string) => `/users/${id}`,
  getEmergecyList: "/emergency-contact",
  createEmegencyContact: "/emergency-contact",
  updateEmegencyContact: (id: string) => `/emergency-contact/${id}`,
  getAdvanceCarePlanList: "/advanced-care-plan",
  createAdvanceCarePaln: "/advanced-care-plan",
  updateAdvanceCarePaln: (id: string) => `/advanced-care-plan/${id}`,
  uploadUrl: "/upload",
  getLivingWillList: "/living-will",
  createLivingWill: "/living-will",
  updateLivingWill: (id: string) => `/living-will/${id}`,
  getPowerOfAttorneyList: "/power-of-attorney",
  createPowerOfAttorneyList: "/power-of-attorney",
  updatePowerOfAttorney: (id: string) => `/power-of-attorney/${id}`,
  getPharmacyList: "/pharmacy",
  createPharmacy: "/pharmacy",
  updatePharmacy: (id: string) => `/pharmacy/${id}`,
  getPrimaryCareProviderList: "primary-care",
  createPrimaryCareProvider: "primary-care",
  updatePrimaryCareProvider: (id: string) => `/primary-care/${id}`,
  getCareGiverList: "/caregivers",
  createCareGiver: "/caregivers",
  updateCareGiver: (id: string) => `/caregivers/${id}`,
  getMedicalReportList: "/other-medical-records",
  createMedicalReport: "/other-medical-records",
  updateMedicalReport: (id: string) => `/other-medical-records/${id}`,
  deleteMedicalRecord: (id: string, recordId: string) =>
    `/other-medical-records/${recordId}/documents/${id}`,
  getMedicationsList: "/medication",
  createMedication: "/medication",
  updateMedication: (id: string) => `/medication/${id}`,
  updatePublicProfileEnable: "/users/public-profile/toggle",
  sharePinValidation: "/users/public-profile/view",
  donePayment: "/account/create-checkout-session",
  requestRefund: "/account/request-refund",
  getPublicProfile: "/users/public-profile",
  getInsuranceList: "/insurance",
  createInsurance: "/insurance",
  updateInsurance: (id: string) => `/insurance/${id}`,
  getDrivingLicenseList: "/drivers-license",
  createDrivingLicense: "/drivers-license",
  updateDrivingLicense: (id: string) => `/drivers-license/${id}`,
  sendQRCode: "/users/send-notify-QrCode",
  getPendingToDoList: "/todos/pending-by-type",
  updateToDoCompletedStatus: (id: string) => `/todos/${id}`,
  getToDoDetailsList: "/todos",

  existingNPIProviderCheck: "/providers/npi-check",
  providerSignup: "/providers/signup",
  requestNewPasswordLinkForProvider: "/providers/request-password-setup",
  existingProviderPhoneCheck: "/providers/check-user-exist",
  getDashboardCount: (selectedDays: string) =>
    `/providers/dashboard?days=${selectedDays}`,
  getDashboardActivePatientDetails: (selectedDays: string) =>
    `/providers/most-active-patients?days=${selectedDays}`,
  getDashboardTaskStats: (selectedDays: string) =>
    `providers/task-stats-by-category?days=${selectedDays}`,
  searchPatient: "/providers/search-patient",
  sendRequestToPatient: "/invitations/send-to-patient",
  cancelProviderSubscription: "/providers/cancel-subscription",
  updateProviderDetails: `/providers/update-info`,
};
