import { Link } from "react-router";
import ScrollToTop from "../scrollToTop/ScrollToTop";

const terms = [
  {
    id: "binding-terms",
    heading: "Binding Terms",
    desc: "This Agreement is a binding legal contract between you and SEVA Healthcare IT LLC (DBA KIT – Keeping It Together). This Agreement takes effect when you either access or use our Services or click an “I Accept” button or check box presented with these terms or, if earlier, when you use any of the Services (the “Effective Date”). You must be minimum 18 years of age and If you are agreeing to these terms on behalf of a party that you represent (e.g., your employer, your business or another entity), you represent and warrant that: (i) you have full legal authority to bind such other party to these terms; (ii) you have read and understand these terms; and (iii) you agree to these terms on behalf of the party that you represent. ",
  },
  {
    id: "medical-advice",
    heading: "Not Medical Treatment or Advice",
    desc: `You understand that <strong> Seva Healthcare IT LLC </strong> is not a healthcare professional and/or healthcare advisor and does not provide medical treatment or advice, nor do we verify the accuracy of any “User Data” (as defined below). The Services are not replacements for proper medical care, and you agree that you (or your caregiver as the case may be), using the App and Services, are solely responsible for obtaining proper treatment for your healthcare conditions. For the purpose of this Agreement, User Data means data generated by or created by you in connection with the use of the App.`,
  },
  {
    id: "agreements",
    heading: "Agreements Incorporated By Reference",
    desc: `In addition to these terms, any other terms and conditions that we post or make available through the Website, apply to your use of App and Services, and are incorporated to, and made a part of these terms. These additional terms include but are not limited to the following: (1) any description located on our Website; (2) our Website terms and Conditions; (3) all Seva Healthcare IT LLC and third-party copyright and trademark notices located on our Website; and (4) our Privacy Notice. For the purpose of the Services provided, the App includes Company’s App more commercially known as “MyKitBuddy” or such other App as offered to you including but not limited to any upgrade, update, enhancement or new version made from time to time.`,
  },
  {
    id: "changes",
    heading: "Changes To These Terms and Services",
    desc: `
    The Company reserves the right to change this Agreement from time to time in its sole discretion without notice to you. The latest version of the Agreement will be posted on the Website and should be reviewed prior to accessing or using the Services. All changes will be effective immediately when posted on the Website and will apply to your use of and access to the Services from that point onward.<br/><br/>
    
    The Services may also change from time to time as the Company enhances, update, or upgrade its existing App or introduces a new version of an App or a new App. The Company reserves the right to modify, withdraw, or discontinue the Services, in whole or in part, at any time without notice to you. You agree that the Company shall have no liability to you or any third party for any losses or damages caused by the Services not being available, in whole or in part, at any time or for any period.
  `,
  },
  {
    id: "account",
    heading: "Account Registration and Deactivation",
    desc: `To access the Services and some features of the Services, you must register for an account (“Account”). When you register for your Account, you may be required to provide us with some information about yourself, such as your name, email address, phone number, date of birth, and a valid form of payment, and you may also provide information about yourself on a voluntary basis (“Account Information”). Account information, and our use and disclosure thereof, are subject to our Privacy Policy. If you connect to any Services with a third-party service, you grant us permission to access and use your information from such third-party service as permitted by that third-party service to store your login credentials for that third-party service. <br/><br/>

SEVA Healthcare IT LLC has implemented two-factor authentications that will help safeguard most vulnerable information and networks. A code or link will be generated and sent directly through a text message or email to your Device. You consent to using such two-factor validation features to access the App.   <br/><br/>

We may, in our sole discretion, refuse to provide or continue providing the Services to any person or entity and change eligibility criteria at any time, including if you fail to comply with these terms. We reserve the right to deactivate, terminate, prevent access to, disable services for, and/or delete any Accounts or access to the Services at any time at our sole discretion. We will not have any liability whatsoever to you for any suspension or termination of your rights under this Agreement, including for termination of your account or deletion of your User Content. If you have registered for an account, you may terminate this Agreement at any time by contacting the Company and requesting termination. `,
  },
  {
    id: "responsibilities",
    heading: "Your Responsibilities in Relation to Devices",
    desc: `The Website and App are configured for certain computers, tablets, smart phones, and/or other electronic devices (each a “Device”), and this Agreement shall apply to any visit, access, registration with, subscription to, and use by you of the Website, the App and/or the Services through any such Devices. We do not guarantee that the Website, the App, the Services, or any portions thereof will function on or in connection with any particular Device, software, operating system, carrier, or network. It is your responsibility to keep the Device updated with the latest version of software and/or operating system from time to time. It is also your responsibility to provide correct and accurate User Data for the App to provide the desired recommendation. Seva Healthcare IT LLC will not be liable for any inaccurate or mistyped User Data and consequences thereon. `,
  },
  {
    id: "subscriptions",
    heading: "Subscriptions",
    desc: `Services and access to Services are purchased as subscriptions. By subscribing to the App, you will receive the Services for a term as per the subscription plan. Currently the Company offers a free plan and a yearly plan for users and a monthly plan for providers. The Company reserves the right to modify the plan from time to time.  
<br/> <br/>
You shall pay all fees or charges to your Account in accordance with the fees, charges, and billing terms in effect at the time a fee or charge is due and payable. If auto-renewal is enabled for the Services you have subscribed for, you will be charged automatically in accordance with the term you selected. We reserve the right to change App and App pricing at any time. We also reserve the right to refuse any order you place with us. If, in our judgment, your purchase constitutes a high-risk transaction, we will require you to provide us with a copy of your valid government-issued photo identification, and possibly a copy of a recent bank statement for the credit or debit card used for the purchase.  `,
  },
  {
    id: "free-trial",
    heading: "Free Trial",
    desc: `If you register an Account for a free trial, the Company will make the applicable Services available to you on a trial basis free of charge until the earlier of (a) the end of the free trial period for which you registered to use the applicable Services, or (b) the start date of any Service Subscriptions ordered by you for such Services, or (c) termination by the Company in its sole discretion. Such Free Trial may be subject to additional terms and conditions as mentioned herein.  <br/> <br/> 

ANY USER DATA YOU ENTER INTO THE SERVICES, DURING YOUR FREE TRIAL WILL BE PERMANENTLY LOST UNLESS YOU PURCHASE A SUBSCRIPTION TO THE SAME SERVICES AS THOSE COVERED BY THE TRIAL, OR PURCHASES APPLICABLE UPGRADED PLANS.  <br/>   <br/> 

DURING THE FREE TRIAL THE SERVICES ARE PROVIDED “AS-IS” WITHOUT ANY WARRANTY AND SEVA HEALTHCARE IT LLC SHALL HAVE NO INDEMNIFICATION OBLIGATIONS NOR LIABILITY OF ANY TYPE WITH RESPECT TO THE SERVICES FOR THE FREE TRIAL PERIOD UNLESS SUCH EXCLUSION OF LIABILITY IS NOT ENFORCEABLE UNDER APPLICABLE LAW IN WHICH CASE SEVA HEALTHCARE IT LLC’S LIABILITY WITH RESPECT TO THE SERVICES PROVIDED DURING THE FREE TRIAL SHALL NOT EXCEED $100.00. WITHOUT LIMITING THE FOREGOING, SEVA HEALTHCARE IT LLC AND ITS AFFILIATES AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT: (A) YOUR USE OF THE SERVICES DURING THE FREE TRIAL PERIOD WILL MEET YOUR REQUIREMENTS, AND YOUR USE OF THE SERVICES DURING THE FREE TRIAL PERIOD WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR. NOTWITHSTANDING ANYTHING CONTAINED IN THE AGREEMENT, YOU SHALL BE FULLY LIABLE UNDER THIS AGREEMENT TO THE COMPANY AND ITS AFFILIATES OR ITS LICENSORS FOR ANY DAMAGES ARISING OUT OF YOUR USE OF THE SERVICES DURING THE FREE TRIAL PERIOD, ANY BREACH BY THIS AGREEMENT AND YOUR INDEMNIFICATION OBLIGATIONS HEREUNDER. YOU SHALL REVIEW THE APPLICABLE SERVICE’S DURING THE TRIAL PERIOD TO BECOME FAMILIAR WITH THE PERFORMANCE OF THE SERVICES BEFORE MAKING A PURCHASE.   `,
  },
  {
    id: "intellectual-property",
    heading: "Seva Health Care IT LLC Intellectual Property Rights",
    desc: "All information and materials, including computer software provided to you by Seva Healthcare IT LLC or otherwise used by Seva Healthcare IT LLC in connection with the Services, that Seva Healthcare IT LLC developed or acquired prior to or independently of this Agreement (the “Seva Healthcare IT LLC Materials”) are and shall remain the property of Seva Healthcare IT LLC or its licensors, which shall retain all intellectual property rights therein. Seva Healthcare IT LLC Materials shall also include derivative works created to the foregoing, even if the derivative works were created as part of the Services. Services or any related intellectual property rights owned or licensed by us. Any rights not expressly granted in this Agreement are reserved by the Company and its licensors.   ",
  },
  {
    id: "license",
    heading: "Seva Health Care IT LLC License To Use The Services",
    desc: "Subject to these terms, Seva Healthcare IT LLC grants you a limited, non-exclusive, and non-transferable license to (a) download, install, and use the App or Services for your personal, non-commercial use on your Device; (b) access, download, and use on such Device is strictly in accordance with these terms; and (c) where appropriate, download, install, use, and/or update the App for your personal, non-commercial use strictly in accordance with these terms.   ",
  },
  {
    id: "license-restrictions",
    heading: "Seva Health Care IT LLC License Restrictions",
    desc: "You shall not (a) copy the App or Services , except as expressly permitted by this license; (b) modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the App or Services ; (c) reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the App or any part thereof; (d) remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices from the App, including any copy thereof; (e) rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the App , or any features or functionality of the App, to any third party for any reason, including by making the App available on a network where it is capable of being accessed by more than one device at any time; or (f) remove, disable, circumvent, or otherwise create or implement any workaround to any copy protection, rights management, or security features in or protecting the App.  ",
  },
  {
    id: "rights-reserved",
    heading: "Rights Reserved",
    desc: "You acknowledge and agree that the App is provided under license, and not sold, to you. You do not acquire any ownership interest in the App under these terms, or any other rights thereto other than to use the App in accordance with the license granted, and subject to all terms, conditions, and restrictions, under these terms. Seva Healthcare IT LLC, its licensors, and service providers reserve and shall retain their entire right, title, and interest in and to the App, including all copyrights, trademarks, and other intellectual property rights therein or relating thereto, except as expressly granted to you in these terms.  ",
  },
  {
    id: "trademark",
    heading: "Trademark Notice",
    desc: "All trademarks, logos, and service marks displayed on the Services are either the Company’s property or the property of third parties. You may not use such trademarks, logos, or service marks without the prior written consent of their respective owners.  ",
  },
  {
    id: "user-content",
    heading: "User Generated Content",
    desc: `The Services may contain interactive features including but not limited to chatrooms, profiles, forums, message boards, intake buttons, QR Code, and other that allow users to post, upload, submit, publish, display, or transmit to other users or other persons content or materials (together, “User Content”) on or through the Services.   <br/>  <br/> 

You are solely responsible for all content, data, information, records, and materials that you submit, upload, transmit, or otherwise make available through the Services (“User Content”), and you assume all risks associated with the use of such User Content.   <br/>  <br/> 

Certain User Content, including but not limited to health information, personal records, and other sensitive data, is treated as confidential within the Services and is not accessible to other users of the Services, except as expressly authorized by you. Such confidential User Content may be accessed only by you, authorized healthcare providers, and authorized provider back-office staff acting on behalf of such providers, in accordance with your permissions, applicable law, and the Company’s Privacy Policy.   <br/>  <br/> 

Except as described above, any User Content you choose to share publicly or with other users through the Services will be considered non-confidential and non-proprietary, and you acknowledge that such content may be viewed, used, or relied upon by others. <br/>  <br/> 

You understand and agree that you bear all risks associated with your User Content, including any reliance on its accuracy, completeness, reliability, or appropriateness by authorized providers, provider staff, other users (where sharing is enabled by you), or third parties, as well as any disclosure of User Content that personally identifies you or any third party. <br/>  <br/> 

You agree that the Company shall not be responsible or liable to any third party for any User Content submitted, posted, or shared by you or any other user of the Services, and the Company does not control, verify, or guarantee the accuracy, completeness, or suitability of any User Content, regardless of its confidentiality status. You further agree that the Company shall not be responsible for any loss or damage incurred as the result of any interactions between you and other users. Your interactions with other users are solely between you and such users. If there is a dispute between you and any other user, we are under no obligation to become involved. <br/> <br/>
User Content must maintain standards and should not a) Infringe intellectual Property Rights b) Promote Illegal Activity or Harm to Others c) Promote sexually explicit material or discrimination d) Fraudulent information or Impersonation e) such other information which from Company’s views are violation of terms, Company reserves the right to either delete or reject such User Content.  

`,
  },
  {
    id: "user-license",
    heading: "User Generated Content License",
    desc: `You hereby grant to the Company an irrevocable, non-exclusive, royalty-free, fully paid, transferable, perpetual, and worldwide license to host, store, reproduce, process, transmit, distribute, display, perform, prepare derivative works of, incorporate into other works, and otherwise use your User Content, solely as necessary to operate, provide, maintain, and improve the Services and to conduct the Company’s business in connect with the services.    <br/>  <br/> 

User Content that includes health information, personal records, or other sensitive data is treated as confidential and is not shared with other users of the Services. Such User Content may be accessed and used only by you, authorized healthcare providers, and authorized provider back-office staff, and only to the extent permitted by your instructions, applicable law, and the Company’s Privacy Policy. The Company will not sell, publicly disclose, or use such confidential User Content for advertising, marketing, or promotional purposes, nor will it share such content with unauthorized third parties. <br/>  <br/>


Notwithstanding the foregoing, you expressly authorize the Company to use and disclose your User Content as reasonably necessary to coordinate care, facilitate transactions, exchange records, and communicate with other healthcare providers or care entities on your behalf, including for referrals, record transfers, eligibility verification, scheduling, billing, or other care-related and administrative purposes consistent with the Services and your permissions. <br/>  <br/>

You represent and warrant that you have all rights, power, and authority necessary to grant the rights granted herein for any User Content you submit, and that such User Content does not violate any law or third-party rights. You acknowledge that you are solely responsible for your User Content and for the consequences of submitting or authorizing its use or disclosure through the Services. You hereby irrevocably waive all claims and have no recourse against us for any alleged or actual infringement or misappropriation of any proprietary rights in any communication, content, or material submitted to us. Please note that all the following licenses are subject to our Privacy Policy to the extent they relate to any User Content that contains any personally identifiable information. 


`,
  },
  {
    id: "third-party-matters",
    heading: "NO RESPONSIBILITY FOR THIRD PARTY MATTERS",
    desc: "Without limiting the provisions of these terms or expanding the scope of Seva Healthcare IT LLC’S responsibilities, Seva Healthcare IT LLC is not responsible for outages or defects in power, telecommunications, Device, third party software, and any other event outside of Seva Healthcare IT LLC’s direct control.  ",
  },
  {
    id: "dispute-resolution",
    heading: "Dispute Resolution & Governing Law",
    desc: `TO THE EXTENT PERMITTED BY APPLICABLE LAW, AND EXCEPT FOR DISPUTES THAT QUALIFY FOR SMALL CLAIMS COURT, ALL DISPUTES ARISING OUT OF OR RELATED TO THESE TERMS OR ANY ASPECT OF THE RELATIONSHIP BETWEEN YOU AND SEVA HEALTHCARE IT LLC, WHETHER BASED IN CONTRACT, TORT, CONSUMER PROTECTION, STATUTE, FRAUD, MISREPRESENTATION OR ANY OTHER LEGAL THEORY (EACH, A “DISPUTE”), WILL BE RESOLVED THROUGH FINAL AND BINDING ARBITRATION BEFORE A NEUTRAL ARBITRATOR INSTEAD OF IN A COURT BY A JUDGE OR JURY, AND YOU AGREE THAT SEVA HEALTHCARE IT LLC AND YOU ARE EACH WAIVING THE RIGHT TO TRIAL BY A JURY. YOU AGREE THAT ANY ARBITRATION UNDER THESE TERMS WILL TAKE PLACE ON AN INDIVIDUAL BASIS. YOU FURTHER AGREE THAT CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED, AND THAT YOU ARE AGREEING TO GIVE UP THE ABILITY TO PARTICIPATE IN A CLASS ACTION.   <br/>  <br/> 

THE ARBITRATION WILL BE ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (“AAA”) UNDER ITS CONSUMER ARBITRATION RULES (CURRENTLY AVAILABLE), AS AMENDED BY THESE TERMS. THE ARBITRATOR WILL CONDUCT HEARINGS, IF ANY, BY TELECONFERENCE OR VIDEOCONFERENCE, RATHER THAN BY PERSONAL APPEARANCES, UNLESS THE ARBITRATOR DETERMINES UPON REQUEST BY YOU OR BY US THAT AN IN-PERSON HEARING IS APPROPRIATE. ANY IN-PERSON APPEARANCES WILL BE HELD AT A MUTUALLY AGREEABLE LOCATION AND IF THE PARTIES ARE UNABLE TO AGREE ON A LOCATION, SUCH DETERMINATION SHOULD BE MADE BY THE AAA OR BY THE ARBITRATOR. THE ARBITRATOR’S DECISION WILL FOLLOW THESE TERMS AND WILL BE FINAL AND BINDING. THE ARBITRATOR WILL HAVE AUTHORITY TO AWARD TEMPORARY, INTERIM OR PERMANENT INJUNCTIVE RELIEF OR RELIEF PROVIDING FOR SPECIFIC PERFORMANCE OF THESE TERMS, BUT ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF WARRANTED BY THE INDIVIDUAL CLAIM BEFORE THE ARBITRATOR. THE AWARD RENDERED BY THE ARBITRATOR MAY BE CONFIRMED AND ENFORCED IN ANY COURT HAVING JURISDICTION. NOTWITHSTANDING ANY OF THE FOREGOING, NOTHING IN THESE TERMS WILL PRECLUDE YOU FROM BRINGING ISSUES TO THE ATTENTION OF FEDERAL, STATE OR LOCAL AGENCIES AND, IF THE LAW ALLOWS, THEY CAN SEEK RELIEF AGAINST US FOR YOU.   <br/>  <br/> 

Some jurisdictions may not allow for arbitration of certain Disputes in certain circumstances. To the extent you are a resident of such jurisdiction, and this arbitration provision is found to be unenforceable by a court within such jurisdiction in connection with a Dispute between you and Seva Healthcare IT LLC, such Dispute will instead, to the extent permitted by applicable law, be resolved exclusively in the federal and state courts located in the Virginia and you and Seva Healthcare IT LLC each waive any jurisdictional, venue, or inconvenient forum objections to such Courts.   <br/> 
<br/>

<strong> Governing Law</strong>: Except to the extent prohibited by applicable law, these terms are governed by the laws of the State of Virginia without regard to its principles of conflicts of law and regardless of your location. 
<br/>
<br/>

<strong>Notice of Dispute</strong>:  In the event of a Dispute arising under, or relating to, these terms, the disputing party must provide the other party with written notice of the Dispute, including the facts giving rise to the Dispute and the relief sought by the disputing party. We will provide such notice by email to your email address. You will provide such notice to Seva Healthcare IT LLC by mail or overnight delivery at the following emai:  <a style={{ textDecoration: "underline", color: "#111" }} href="mailto:contact@mykitbuddy.com"> contact@mykitbuddy.com</a>

.
<br/>
<br/>
<strong>Equitable Relief</strong>: Any violation of a party’s intellectual or industrial property rights will cause the non-violating party irreparable harm for which monetary damages are an inadequate remedy, and the non-violating party is entitled to temporary, preliminary, and permanent injunctive relief and specific performance without the posting of bond or other security, or if required, the minimum bond or security required. `,
  },
  {
    id: "disclaimer",
    heading: "Disclaimer",
    desc: `EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW, AND EXCEPT FOR ANY LIMITED WARRANTY INCLUDED IN THE APPLICABLE APP’S LABELING, THE APPS AND SERVICES ARE PROVIDED “AS-IS” AND ON AN “AS AVAILABLE” BASIS WITHOUT ANY WARRANTY, EXPRESS OR IMPLIED, AND YOU USE THE APPS AND SERVICES AT YOUR OWN RISK.  <br/> <br/>

EXCEPT TO THE EXTENT THAT SUCH LIMITATION IS PROHIBITED UNDER APPLICABLE LAW, SEVA HEALTHCARE IT LLC DISCLAIMS ALL IMPLIED WARRANTIES OR CONDITIONS, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A SPECIFIC PURPOSE OR USE, QUIET ENJOYMENT, ACCURACY, OPERATION, COMPLIANCE WITH DOCUMENTATION AND NON-INFRINGEMENT. SEVA HEALTHCARE IT LLC DISCLAIMS, AND THESE TERMS DO NOT INCLUDE, THE PROVISIONS OF THE UNIFORM COMPUTER INFORMATION TRANSACTIONS ACT, THE UNIFORM COMMERCIAL CODE, THE UN CONVENTION ON CONTRACTS FOR THE INTERNATIONAL SALE OF GOODS, AND ANY OTHER PROVISIONS IMPLIED INTO THESE TERMS IF NOT DISCLAIMED.   <br/> <br/>

SEVA HEALTHCARE IT LLC DOES NOT MAKE ANY WARRANTIES THAT THE APPS OR SERVICES OR ANY DATA OR REPORTS PROVIDED BY SEVA HEALTHCARE IT LLC, WILL MEET YOUR REQUIREMENTS, BE RETRIEVABLE, UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE OR THAT ALL ERRORS WILL BE CORRECTED.   <br/> <br/>

SEVA HEALTHCARE IT LLC DOES NOT MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE APPS OR SERVICES.   <br/> <br/>

SEVA HEALTHCARE IT LLC DOES NOT WARRANT ANY DEVICE, SOFTWARE, SERVICE OR DATA THAT YOU MAY USE IN CONNECTION WITH ANY APP OR SERVICE, WHETHER OR NOT SUCH THIRD-PARTY ITEM IS DESCRIBED IN, OR AVAILABLE OR CAN BE CONNECTED TO THROUGH, ANY APP OR SERVICE.   <br/> <br/>

NO INFORMATION OR COMMUNICATIONS, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM OR THROUGH SEVA HEALTHCARE IT LLC OR THE APPS AND SERVICES WILL CREATE ANY WARRANTY, EXCEPT FOR ANY LIMITED WARRANTY INCLUDED IN THE APPLICABLE APP’S LABELING. THIS DOES NOT APPLY TO YOUR RIGHTS WITH RESPECT TO DEFECTIVE OR FAULTY SEVA HEALTHCARE IT LLC APPS. <br/> <br/>

EXCEPT AS EXPRESSLY PROVIDED, SEVA HEALTHCARE IT LLC DOES NOT WARRANT THE ACCURACY OF ANY APP OR SERVICE, AND THE USER DATA UPLOADED FROM ANY APP OR SERVICE AND RECEIVED BY SEVA HEALTHCARE IT LLC IS PROVIDED TO THE USER “AS-IS.” SEVA HEALTHCARE IT LLC DOES NOT ASSUME ANY OBLIGATION TO, AND DOES NOT WARRANT THAT IT WILL, CREATE OR INCLUDE ADDITIONAL FEATURES OR FUNCTIONALITY FOR THE APPS OR SERVICES.   <br/> <br/>

EXCEPT AS INCLUDED IN ANY APP LABELING, AND WITHOUT LIMITING YOUR RIGHTS UNDER APPLICABLE LAW, IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE APPS OR SERVICES, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE THEIR USE.   `,
  },
  {
    id: "liability",
    heading: "Limitations on Liability",
    desc: `TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, IN NO EVENT WILL INTELXCEL’S AFFILIATES, LICENSORS, SUPPLIERS AND OTHER THIRD PARTIES WITH WHICH INTELXCEL HAS A CONTRACTUAL RELATIONSHIP (INCLUDING ITS AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, CONSULTANTS, AND AGENTS) HAVE ANY LIABILITY WHATSOEVER ARISING FROM OR RELATING TO THE APPS AND SERVICES, OR THESE TERMS, WHETHER FOR DIRECT OR ANY OTHER TYPE OF DAMAGES WHATSOEVER.  <br/> <br/> 

EXCEPT TO THE EXTENT THAT SUCH LIMITATION IS PROHIBITED UNDER APPLICABLE LAW, NEITHER SEVA HEALTHCARE IT LLC, IT’S AFFILIATES, NOR ITS OR THEIR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR SUPPLIERS (COLLECTIVELY, “SEVA HEALTHCARE IT LLC PARTIES”) SHALL BE LIABLE FOR ANY DAMAGES ARISING FROM THE USE OF OR INABILITY TO USE THE APPS OR SERVICES.  <br/><br/>

EXCEPT TO THE EXTENT THAT SUCH LIMITATION IS PROHIBITED UNDER APPLICABLE LAW, NONE OF THE SEVA HEALTHCARE IT LLC PARTIES SHALL BE LIABLE FOR ANY CONSEQUENTIAL, UNFORESEEABLE, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES OR DAMAGES RESULTING FROM LOSS OF USER DATA OR BUSINESS INTERRUPTION WHETHER THE CLAIM OR DAMAGES ARE BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), EXTRA-CONTRACTUAL LIABILITY, STRICT LIABILITY OR ANY OTHER LEGAL THEORY, EVEN IF SEVA HEALTHCARE IT LLC, ITS AFFILIATES OR A PERSON AFFILIATED WITH EITHER OF THEM HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES EXCLUDED IN THIS SECTION, AND EVEN IF SUCH EXCLUSIONS CAUSE THESE TERMS OR ANY REMEDY TO FAIL OF ITS ESSENTIAL PURPOSE.  <br/><br/>

EXCEPT TO THE EXTENT THAT SUCH LIMITATION IS PROHIBITED UNDER APPLICABLE LAW, NONE OF THE SEVA HEALTHCARE IT LLC PARTIES SHALL BE LIABLE FOR TOTAL DAMAGES FOR ALL CLAIMS ARISING FROM OR RELATING TO THESE TERMS, THE APPS OR SERVICES IN AN AGGREGATE AMOUNT GREATER THAN $100 U.S. DOLLARS.  <br/><br/>

 EXCEPT TO THE EXTENT THAT SUCH EXCLUSION OR LIMITATION IS PROHIBITED UNDER APPLICABLE LAW, NONE OF THE SEVA HEALTHCARE IT LLC PARTIES SHALL BE LIABLE FOR THE ACTIONS OR OMISSIONS OF A USER OR ANY THIRD PARTY.  <br/><br/>

SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS AND DISCLAIMERS MAY NOT APPLY TO YOU, AND YOU MAY HAVE CERTAIN ADDITIONAL RIGHTS. TO THE EXTENT THAT WE MAY NOT, AS A MATTER OF APPLICABLE LAW, DISCLAIM ANY IMPLIED WARRANTY OR LIMIT OUR LIABILITIES, THE SCOPE AND DURATION OF SUCH WARRANTY AND THE EXTENT OF OUR LIABILITY WILL BE THE MINIMUM PERMITTED UNDER SUCH APPLICABLE LAW, AND THESE TERMS WILL BE DEEMED MODIFIED TO THE MINIMUM EXTENT NECESSARY TO COMPLY WITH SUCH APPLICABLE LAW. `,
  },
  {
    id: "indemnification",
    heading: "Your Indemnification",
    desc: "Except to the extent prohibited under applicable law, you agree to indemnify, defend and hold harmless Seva Healthcare IT LLC, our Affiliates, licensors, suppliers and other contract relationships (including the officers, directors, employees, consultants, and agents of each) from and against any and all third-party claims, liabilities, damages, losses, costs, expenses, fees (including reasonable attorneys’ fees and court costs) that such parties may incur as a result of or arising from (1) any information you submit, post or transmit through any App, (2) your use of the App and Services, (3) your violation of these terms, or (4) your violation of any rights of any other person or entity.   ",
  },
  {
    id: "privacy",
    heading: "Privacy",
    desc: `For information about how the Company collects, uses, and shares your information, please review our Privacy Policy. You agree that by using the Services you consent to the collection, use, and sharing (as set forth in the Privacy Policy) of such information.
<br/><br/>
<strong> The Children’s Online Privacy Protection Act requires that online Seva Healthcare IT LLC obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13 years old. We do not knowingly collect or solicit personally identifiable information from children under 13 years old. If you are a child under 13 years old, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn we have collected personal information from a child under 13 years old, we will delete that information as quickly as possible. If you believe that a child under 13 years old may have provided us personal information, please contact us at contact@mykidbuddy.com.   `,
  },

  {
    id: "other-terms",
    heading: "Other Terms",
    desc: ` <strong>Notices</strong>: Except as expressly provided elsewhere in these terms, we will provide any notice under these terms by email to your email address. You will provide any notice under this Agreement these terms to Seva Healthcare IT LLC by mail or overnight delivery at the following address:   
    <a style={{ textDecoration: "underline", color: "#111" }} href="mailto:contact@mykitbuddy.com"> contact@mykitbuddy.com</a>

<br/><br/> <strong>Questions or Complaints</strong>: If you have a question or complaint regarding anSeva Healthcare IT LLC App or  Service please mail to <a style={{ textDecoration: "underline", color: "#111" }} href="mailto:contact@mykitbuddy.com"> contact@mykitbuddy.com</a>. 

<br/><br/> <strong>Feedback to Seva Healthcare IT LLC</strong>: You may provide Feedback to us and, in doing so, you grant to us the worldwide, nonexclusive, unrestricted, perpetual, irrevocable (on any basis whatsoever), royalty free right for us to use such Feedback in any way we determine, including through third parties, without any obligation to you for compensation, attribution, accounting, or otherwise. You will only provide to us Feedback for which you have the right to grant to us the rights listed in the preceding sentence.

<br/><br/> <strong>Severability</strong>: In the event that any court holds any provision of these terms to be void, invalid or unenforceable, such provision will be modified to the minimum extent necessary to be effective, valid and enforceable while preserving the original intentions of the parties to the greatest extent possible, and the other provisions of these terms will remain in full force and effect and enforceable according to their terms. 

<br/><br/> <strong>Assignment</strong>: We may assign these terms in whole or in part at any time without notice (except to the extent such notice is mandatory under applicable law, in which case such notice may be made via a posting to our Website). You may not assign your rights in these terms with respect to your use of the Apps or Services. 

<br/><br/> <strong>Export Restrictions</strong>: The Apps and Services may be subject to US export control laws, including the Export Control Reform Act and its associated regulations. You shall not, directly or indirectly, export, re-export, or release the Apps or Services to, or make the Apps and Services accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, rule, or regulation. You shall comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Apps and Services available outside the US. 

<br/><br/> <strong>Relationship / No Third-Party Beneficiaries</strong>:  Our relationship with you is as an independent contractor, and nothing in these terms creates an agency or partnership. Except for Seva Healthcare IT LLC’s Licensors, Apple and Apple’s subsidiaries, Google and Google subsidiaries there are no third-party beneficiaries to these terms. 

<br/><br/> <strong>Complete Agreement</strong>: These terms are the complete and final agreement between the parties relating to the matters herein and they supersede any prior agreements or communications between the parties and may only be modified as described in these terms. Seva Healthcare IT LLC’s failure to exercise or enforce any right or provision of these terms will not constitute a waiver of such right or provision. The section titles in these terms are for convenience only and have no legal or contractual effect. In the event of a conflict between these terms and any other terms, these terms shall govern. `,
  },
];

const TermsNConditionPage = () => {
  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };
  return (
    <>
      <div className="flex flex-col items-center border-b bg-[#FFFFFF] pb-4 sticky top-0 z-10">
        <Link to="/" className="flex items-center gap-2 cursor-pointer">
          <img
            src="/../icons/kit-logo-icon.svg"
            alt="logo"
            className="w-18 h-12 mt-2"
          />
        </Link>
      </div>
      <main className="min-h-screen bg-[#FAFEFF] ">
        <ScrollToTop />

        <div className="privacy-policy-page font-mona">
          <div className="container">
            <h1 className="text-xl sm:text-2xl font-bold  text-center  leading-snug  wrap-break-word  px-4">
              SEVA Healthcare IT LLC (DBA KIT – Keeping It Together)
            </h1>

            <h2 className="text-lg sm:text-xl font-semibold text-center">
              TERMS OF USE
            </h2>
            <div className="row" style={{ padding: "0 1.5rem" }}>
              <div className="col-lg-12">
                <p>
                  This terms of the Services Agreement (the “Agreement”)
                  contains the terms and conditions that govern your access to
                  and use of the Services (as defined below). This Agreement is
                  made and entered into by and between you and Seva Healthcare
                  IT LLC (“DBA KIT – Keeping It Together”, “Company”, “us”,
                  “we”, or “our”). This Agreement sets forth the terms and
                  conditions that govern your use of and access to the Website
                  and any program, Apps, devices, materials, software,
                  application (the “App”), and services provided by us
                  (collectively, the “Services”). By clicking “I Agree,”
                  creating an account, downloading, installing, accessing, or
                  using any part of the Services provided by SEVA Healthcare IT
                  LLC, you agree to be legally bound by this Comprehensive End
                  User Terms of Use Master Agreement (“Agreement”). If you do
                  not agree, do not use the Services.
                </p>

                <div className="mx-auto max-w-3xl">
                  <h2 className="mb-4 text-lg font-semibold text-black">
                    WHAT THESE TERMS CONTAIN
                  </h2>
                  <div className="mt-4 overflow-hidden rounded-lg border border-[#E5E7EB] bg-white ">
                    <table className="w-full border-collapse text-sm">
                      <thead className="bg-[#00BCD4] text-white">
                        <tr>
                          <th className="w-[60px] px-2 py-2 text-left font-medium">
                            Sl No
                          </th>
                          <th className=" px-3 py-2 text-left font-medium">
                            Heading
                          </th>
                        </tr>
                      </thead>

                      <tbody>
                        {terms.map((term, index) => (
                          <tr
                            key={term.id}
                            className="border-b last:border-b-0 hover:bg-[#F7FAFF]"
                          >
                            <td className="px-3 py-2 text-gray-700">
                              {index + 1}
                            </td>

                            <td className="px-3 py-2">
                              <button
                                onClick={() => scrollToSection(term.id)}
                                className="text-left text-[#1F2937] underline underline-offset-2 "
                              >
                                {term.heading}
                              </button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
                {/* Sections for each term */}
                <div>
                  {terms.map((term, idx) => (
                    <section
                      id={term.id}
                      key={term.id}
                      className="mt-12 scroll-mt-[90px]"
                    >
                      <h4 style={{ fontWeight: "700" }}>
                        {idx + 1}. <span>{term.heading}</span>
                      </h4>
                      <p dangerouslySetInnerHTML={{ __html: term.desc }} />
                    </section>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="w-full py-6 text-center bg-[#FFFFFF] border-t font-mona font-normal text-sm text-[#000000]">
        © 2025 KIT — Keeping It Together™
      </footer>
    </>
  );
};

export default TermsNConditionPage;
