export const ROUTES = {
  auth: {
    createAccount: "create-account",
    parentDetails: "parent-details",
    sharePin: "share-pin",
    resetPasswordMsg: "reset-password-msg",
    newPassword: "new-password",
    registration: "registration",
    login: "login",
    forgotPassword: "forgot-password",
    otpVerify: "verify-otp",
    success: "success-page",
    accountVerification: "account-verification",
    subscription: "subscription",
    createProviderAccount: "create-provider-account",
    resetPasswordMsgForProvider: "reset-password-msg-for-provider",
  },
  role: {
    patient: "patient",
    provider: "provider",
  },
  provider: {
    dashboard: "dashboard",
    analytics: "analytics",
    patients: "patients",
    help: "help",
    settings: "settings",
    subscription: "subscription",
    addPatient: "add-patient",
    patientsDetails: "patients-details",
    createToDo: "create-todo",
    completeToDo: "complete-todo",
  },
  patient: {
    dashboard: "dashboard",
    publicHealthProfile: "public-health-profile",
    shareProfile: "share-profile",
    symptoms: "symptoms",
    medications: "medications",
    todoList: "todo-list",
    toDodetails: "details",
    personalInformation: "personal-information",
    allergies: "allergies",
    insurance: "insurance",
    emergencyContact: "emergency-contact",
    advancePlan: "advance-plan",
    livingWill: "living-will",
    powerofAttorney: "power-of-attorney",
    pharmacy: "pharmacy",
    primaryCareProvider: "primary-care-provider",
    caregiver: "caregiver",
    driverLicense: "driver-license",
    medicalReport: "medical-report",
    privacySettings: "privacy-settings",
    accountSettings: "account-settings",
    subscription: "subscription",
  },
  public: {
    profile: "profile",
  },
};
